server:
  # 端口
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: console
  # 数据源配置
  datasource:
    # 使用MySQL5.7，如果是版本8以上，需要修改驱动和url
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demoproject?useUnicode=true&useSSL=false&characterEncoding=utf8
    # mysql5.7以上的版本
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: L,%o11My<:#W
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8091
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: strawberry #命名空间
        group: DEFAULT_GROUP   # 分组
        cluster-name: BJ
        metadata:
          version: v3


  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 192.168.10.100
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    password: root
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 192.168.10.100
    # 端口
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.lychee.textserver.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.lychee.textserver.mapper: debug
